<a href="https://colab.research.google.com/github/aayushchourasia123/Machine-Learning/blob/main/Binning%20and%20Binarization/Binarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import numpy as np
import pandas as pd

In [70]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.compose import ColumnTransformer

In [71]:
df=pd.read_csv('train.csv')[['Age','Fare','SibSp','Parch','Survived']]

In [72]:
df

      Age     Fare  SibSp  Parch  Survived
0    22.0   7.2500      1      0         0
1    38.0  71.2833      1      0         1
2    26.0   7.9250      0      0         1
3    35.0  53.1000      1      0         1
4    35.0   8.0500      0      0         0
..    ...      ...    ...    ...       ...
886  27.0  13.0000      0      0         0
887  19.0  30.0000      0      0         1
888   NaN  23.4500      1      2         0
889  26.0  30.0000      0      0         1
890  32.0   7.7500      0      0         0

[891 rows x 5 columns]

In [73]:
df.dropna(inplace=True)

In [74]:
df['family']=df['SibSp']+df['Parch']

In [75]:
df.head()

    Age     Fare  SibSp  Parch  Survived  family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [76]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [77]:
df

      Age     Fare  Survived  family
0    22.0   7.2500         0       1
1    38.0  71.2833         1       1
2    26.0   7.9250         1       0
3    35.0  53.1000         1       1
4    35.0   8.0500         0       0
..    ...      ...       ...     ...
885  39.0  29.1250         0       5
886  27.0  13.0000         0       0
887  19.0  30.0000         1       0
889  26.0  30.0000         1       0
890  32.0   7.7500         0       0

[714 rows x 4 columns]

In [78]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [79]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [85]:
x_train.head()

      Age     Fare  family
328  31.0  20.5250       2
73   26.0  14.4542       1
253  30.0  16.1000       1
719  33.0   7.7750       0
666  25.0  13.0000       0

In [81]:
#without binarization
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
accuracy_score(y_test,y_pred)

0.6363636363636364

In [82]:
np.mean(cross_val_score(DecisionTreeClassifier(),x,y,cv=10,scoring='accuracy'))

np.float64(0.6457159624413146)

In [83]:
#using binarizer
from sklearn.preprocessing import Binarizer

#threshold- float, default=0.0
#Feature values below or equal to this are replaced by 0, above it by 1. Threshold may not be less than 0 for operations on sparse matrices.

trf=ColumnTransformer([('bins',Binarizer(copy=False),['family'])],remainder="passthrough")
x_train_trf=trf.fit_transform(x_train)
x_test_trf=trf.transform(x_test)

In [84]:
pd.DataFrame(x_train_trf,columns=['family','Age','Fare']) #1 if not traveling alone
                                                          #0 if traveling alone

     family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [86]:
clf=DecisionTreeClassifier()
clf.fit(x_train_trf,y_train)
y_pred2=clf.predict(x_test_trf)
accuracy_score(y_test,y_pred2)

0.6223776223776224

In [88]:
x_trf=trf.fit_transform(x)
np.mean(cross_val_score(DecisionTreeClassifier(),x_trf,y,cv=10,scoring='accuracy'))

np.float64(0.6290297339593114)