<a href="https://colab.research.google.com/github/aayushchourasia123/Machine-Learning/blob/main/Iterative%20imputer/iterative_imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [65]:
 df = pd.DataFrame({
    'R&D spend': [8,np.nan,15,12,2],
    'administration': [15, 5,10,np.nan,15],
    'marketing spend ': [30,20,41,26,np.nan],
    'profit' : [11,9,19,13,7]
})
df

   R&D spend  administration  marketing spend   profit
0        8.0            15.0              30.0      11
1        NaN             5.0              20.0       9
2       15.0            10.0              41.0      19
3       12.0             NaN              26.0      13
4        2.0            15.0               NaN       7

In [66]:
x = df.drop('profit',axis=1)
y = df['profit']

In [67]:
x

   R&D spend  administration  marketing spend
0        8.0            15.0              30.0
1        NaN             5.0              20.0
2       15.0            10.0              41.0
3       12.0             NaN              26.0
4        2.0            15.0               NaN

In [68]:
lr = LinearRegression()
# I'm using Linear Regression because all the features are highly correlated with each other
# In most real life datasets, they will be not, and the need will arise to use other regressors

imp = IterativeImputer(estimator=lr, verbose=2, max_iter=100, imputation_order='roman')
# play around with the max_iter and tol parameters to get a better feel of how it is working

In [69]:
# to find "scaled tolerance", multiply the tolerance with the max of the absolute values
# in the original dataset
1e-3 * 41  #tol by default 1e-3

0.041

In [70]:
imp.fit_transform(x)

[IterativeImputer] Completing matrix with shape (5, 3)
[IterativeImputer] Ending imputation round 1/100, elapsed time 0.00
[IterativeImputer] Change: 13.89158650678614, scaled tolerance: 0.041
[IterativeImputer] Ending imputation round 2/100, elapsed time 0.01
[IterativeImputer] Change: 7.788589474908854, scaled tolerance: 0.041
[IterativeImputer] Ending imputation round 3/100, elapsed time 0.01
[IterativeImputer] Change: 23.948920418409116, scaled tolerance: 0.041
[IterativeImputer] Ending imputation round 4/100, elapsed time 0.01
[IterativeImputer] Change: 7.612848445225012, scaled tolerance: 0.041
[IterativeImputer] Ending imputation round 5/100, elapsed time 0.01
[IterativeImputer] Change: 0.27235443705797024, scaled tolerance: 0.041
[IterativeImputer] Ending imputation round 6/100, elapsed time 0.02
[IterativeImputer] Change: 0.012786770349407561, scaled tolerance: 0.041
[IterativeImputer] Early stopping criterion reached.

array([[ 8.        , 15.        , 30.        ],
       [26.7182251 ,  5.        , 20.        ],
       [15.        , 10.        , 41.        ],
       [12.        , 13.02245793, 26.        ],
       [ 2.        , 15.        , 70.6926375 ]])