<a href="https://colab.research.google.com/github/aayushchourasia123/Machine-Learning/blob/main/one%20hot%20encoding/one_hot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
import numpy as np

In [38]:
df=pd.read_csv('/content/cars.csv')

In [39]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [40]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [41]:
df['brand'].nunique() #number of brands

32

In [42]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

one hot encoding using pandas

In [43]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [44]:
#as we have studyed in dummy variable trap
#it drops 1st category from both fuel and owner
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

one hot encoding using sklearn

In [45]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [46]:
df2=df.iloc[:,0:4]
df2

        brand  km_driven    fuel                 owner
0      Maruti     145500  Diesel           First Owner
1       Skoda     120000  Diesel          Second Owner
2       Honda     140000  Petrol           Third Owner
3     Hyundai     127000  Diesel           First Owner
4      Maruti     120000  Petrol           First Owner
...       ...        ...     ...                   ...
8123  Hyundai     110000  Petrol           First Owner
8124  Hyundai     119000  Diesel  Fourth & Above Owner
8125   Maruti     120000  Diesel           First Owner
8126     Tata      25000  Diesel           First Owner
8127     Tata      25000  Diesel           First Owner

[8128 rows x 4 columns]

In [47]:
from sklearn.preprocessing import OneHotEncoder

In [48]:
 #we use sparse=false as now it will return numpy array
#to drop 1 column from both fuel and owner use  ohe=OneHotEncoder(drop='first',sparse='False')
# if you dont add dtype bydefault all values will be float
ohe = OneHotEncoder(sparse_output=False,dtype=np.int32)

In [49]:
df2_new=ohe.fit_transform(df2[['fuel','owner']])

In [50]:
#this new df2_new only have dummy variable of fuel and owner brand and km_driven we have to append
df2_new.shape

(8128, 9)

In [56]:
np.hstack([df2[['brand','km_driven']],df2_new])

array([['Maruti', 145500, 0, ..., 0, 0, 0],
       ['Skoda', 120000, 0, ..., 1, 0, 0],
       ['Honda', 140000, 0, ..., 0, 0, 1],
       ...,
       ['Maruti', 120000, 0, ..., 0, 0, 0],
       ['Tata', 25000, 0, ..., 0, 0, 0],
       ['Tata', 25000, 0, ..., 0, 0, 0]], dtype=object)

One hot encoding for multiple category

In [64]:
counts=df['brand'].value_counts()

In [68]:
threshold=100

In [71]:
rep1=counts[counts<=threshold].index

In [72]:
#cars less than 100 are categories as uncommon
pd.get_dummies(df['brand'].replace(rep1,'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False